<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ExercisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('exercises')->insert([
            [
                'id' => 1,
                'name' => 'Leg Extension',
                'image' => 'leg_extension.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 2,
                'name' => 'Pressa 45°',
                'image' => 'pressa_45.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 3,
                'name' => 'Hack Squat',
                'image' => 'hack_squat.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 4,
                'name' => 'Leg Curl',
                'image' => 'leg_curl.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 5,
                'name' => 'Leg Curl Seduto',
                'image' => 'leg_curl_seduto.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 6,
                'name' => 'Calf Machine In Piedi',
                'image' => 'calf_machine.png',
                'description' => 'Placeholder',
                'muscle' => 'Polpacci',
            ],
            [
                'id' => 8,
                'name' => 'Affondi Corpo Libero',
                'image' => 'affondi_corpo_libero.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 9,
                'name' => 'Affondi Bulgari Con Manubri',
                'image' => 'affondi_bulgari_manubri.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 10,
                'name' => 'Squat Al Multipower',
                'image' => 'squat_multipower.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 11,
                'name' => 'Leg Press',
                'image' => 'leg_press.png',
                'description' => 'Placeholder',
                'muscle' => 'Quadricipiti',
            ],
            [
                'id' => 12,
                'name' => 'Calf In Piedi Singolo',
                'image' => 'calf_in_piedi_singolo.png',
                'description' => 'Placeholder',
                'muscle' => 'Polpacci',
            ],
            [
                'id' => 13,
                'name' => 'Calf Con Bilanciere Seduto',
                'image' => 'calf_con_bilanciere_seduto.png',
                'description' => 'Placeholder',
                'muscle' => 'Polpacci',
            ],
            [
                'id' => 14,
                'name' => 'Calf Machine Seduto',
                'image' => 'calf_machine_seduto.png',
                'description' => 'Placeholder',
                'muscle' => 'Polpacci',
            ],
            [
                'id' => 15,
                'name' => 'Calf In Piedi Con Manubri',
                'image' => 'calf_in_piedi_manubri.png',
                'description' => 'Placeholder',
                'muscle' => 'Polpacci',
            ],
            [
                'id' => 16,
                'name' => 'Stacchi Gambe Tese',
                'image' => 'stacchi_gambe_tese.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 17,
                'name' => 'Leg Curl In Piedi',
                'image' => 'leg_curl_in_piedi.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 18,
                'name' => 'Leg Curl Cavo Basso',
                'image' => 'leg_curl_cavo_basso.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 19,
                'name' => 'Leg Curl In Quadrupedia Cavo Basso',
                'image' => 'leg_curl_quadrupedia_cavo_basso.png',
                'description' => 'Placeholder',
                'muscle' => 'Femorali',
            ],
            [
                'id' => 20,
                'name' => 'Scrollate Al Multi Lift',
                'image' => 'scrollate_multi_lift.png',
                'description' => NULL,
                'muscle' => 'Trapezi',
            ],
            [
                'id' => 21,
                'name' => 'Tirate Al Mento Con Bilanciere',
                'image' => 'tirate_al_mento_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Trapezi',
            ],
            [
                'id' => 22,
                'name' => 'Tirate Al Mento Al Cavo Basso',
                'image' => 'tirate_al_mento_cavo_basso.png',
                'description' => NULL,
                'muscle' => 'Trapezi',
            ],
            [
                'id' => 23,
                'name' => 'Tirate Al Mento Con Manubri',
                'image' => 'tirate_al_mento_manubri.png',
                'description' => NULL,
                'muscle' => 'Trapezi',
            ],
            [
                'id' => 24,
                'name' => 'Dips Gambe Distese',
                'image' => 'dips_gambe_distese.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 25,
                'name' => 'Kickback 90° Con Manubri',
                'image' => 'kickback_90_manubri.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 26,
                'name' => 'Distensioni Presa Stretta Al Multipower',
                'image' => 'distensioni_strette_multipower.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 27,
                'name' => 'French Press Seduto Un Braccio',
                'image' => 'french_press_seduto_un_braccio.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 28,
                'name' => 'French Press Un Braccio Panca Piana',
                'image' => 'french_press_singolo_panca_piana_manubri.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 29,
                'name' => 'French Press Panca Piana',
                'image' => 'french_press_panca_piana.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 30,
                'name' => 'French Press Bilanciere Panca Piana',
                'image' => 'french_press_bilanciere_panca_piana.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 31,
                'name' => 'French Press Con Manubrio Seduto',
                'image' => 'french_press_manubrio_seduto.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 32,
                'name' => 'Push Down Al Cavo Alto',
                'image' => 'push_down_cavo_alto.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 33,
                'name' => 'Spinte Bilanciere Presa Stretta Panca Piana',
                'image' => 'spinte_bilanciere_presa_stretta_panca_piana.png',
                'description' => NULL,
                'muscle' => 'Tricipiti',
            ],
            [
                'id' => 34,
                'name' => 'Alzate Laterali 90° Seduto',
                'image' => 'alzate_lat_90_seduto.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 35,
                'name' => 'Aperture Laterali Deltoid Machine',
                'image' => 'aperture_lat_deltoid_machine.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 36,
                'name' => 'Military Press Seduto',
                'image' => 'military_press_seduto.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 37,
                'name' => 'Volare Su Panca Inversa',
                'image' => 'volare_panca_inversa.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 38,
                'name' => 'Alzate Laterali In Piedi',
                'image' => 'alzate_lat_in_piedi.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 39,
                'name' => 'Alzate Laterali Seduto',
                'image' => 'alzate_lat_seduto.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 40,
                'name' => 'Peck Back Inversa',
                'image' => 'peck_back_inverso.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 41,
                'name' => 'Military Press Al Multipower',
                'image' => 'military_press_al_multipower.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 42,
                'name' => 'Shoulder Press',
                'image' => 'shoulder_press.png',
                'description' => NULL,
                'muscle' => 'Spalle',
            ],
            [
                'id' => 43,
                'name' => 'Croci Su Panca Piana',
                'image' => 'croci_panca_piana.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 44,
                'name' => 'Chest Press',
                'image' => 'chest_press.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 45,
                'name' => 'Chiusure Ai Cavi Bassi',
                'image' => 'chiusure_cavi_bassi.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 46,
                'name' => 'Peck Back',
                'image' => 'peck_back.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 47,
                'name' => 'Distensioni Panca Inclinata Al Multipower',
                'image' => 'distensioni_panca_inclinata_multipower.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 48,
                'name' => 'Distensioni Panca Piana Al Multipower',
                'image' => 'distensioni_panca_piana_multipower.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 49,
                'name' => 'High Chest Machine',
                'image' => 'high_chest_machine.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 50,
                'name' => 'Super Declined Chest Press',
                'image' => 'super_declined_chest_press.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 51,
                'name' => 'Distensioni A Terra',
                'image' => 'distensioni_a_terra.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 52,
                'name' => 'Spinte Su Panca Piana',
                'image' => 'spinte_panca_piana.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 53,
                'name' => 'Spinte Panca Piana Con Bilanciere',
                'image' => 'spinte_panca_piana_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 54,
                'name' => 'Spinte Su Panca Inclinata',
                'image' => 'spinte_panca_inclinata.png',
                'description' => NULL,
                'muscle' => 'Pettorali',
            ],
            [
                'id' => 55,
                'name' => 'Sumo Squat Con Manubrio',
                'image' => 'sumo_squat_manubrio.png',
                'description' => NULL,
                'muscle' => 'Glutei',
            ],
            [
                'id' => 56,
                'name' => 'Sumo Squat A Corpo Libero',
                'image' => 'sumo_squat_corpo_libero.png',
                'description' => NULL,
                'muscle' => 'Glutei',
            ],
            [
                'id' => 57,
                'name' => 'Bridge Su Panca Con Bilanciere',
                'image' => 'bridge_su_panca_con_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Glutei',
            ],
            [
                'id' => 58,
                'name' => 'Slanci Posteriori In Piedi',
                'image' => 'slanci_posteriori_in_piedi.png',
                'description' => NULL,
                'muscle' => 'Glutei',
            ],
            [
                'id' => 59,
                'name' => 'Hypextension',
                'image' => 'hypextension.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 60,
                'name' => 'Lat Machine Avanti',
                'image' => 'lat_machine_avanti.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 61,
                'name' => 'Lat Machine Presa Inversa',
                'image' => 'lat_machine_presa_inversa.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 62,
                'name' => 'Lat Machine Con Trazibar',
                'image' => 'lat_machine_trazibar.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 63,
                'name' => 'Pulley Basso',
                'image' => 'pulley_basso.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 64,
                'name' => 'Pulley Presa Inversa',
                'image' => 'pulley_presa_inversa.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 65,
                'name' => 'Pulley Con Trazibar',
                'image' => 'pulley_trazibar.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 66,
                'name' => 'Pulley Con Triangolo',
                'image' => 'pulley_triangolo.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 67,
                'name' => 'Rematore Con Bilanciere',
                'image' => 'rematore_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 68,
                'name' => 'Rematore High Row',
                'image' => 'rematore_high_row.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 69,
                'name' => 'Rematore Su Panca Con Manubrio',
                'image' => 'rematore_manubrio_su_panca.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 70,
                'name' => 'Rematore Al Multipower',
                'image' => 'rematore_multipower.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 71,
                'name' => 'T Bar',
                'image' => 'tbar.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 72,
                'name' => 'Trazioni Presa A Martello',
                'image' => 'trazioni_presa_hammer.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 73,
                'name' => 'Trazioni Presa Inversa',
                'image' => 'trazioni_presa_inversa.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 74,
                'name' => 'Trazioni',
                'image' => 'trazioni.png',
                'description' => NULL,
                'muscle' => 'Dorsali',
            ],
            [
                'id' => 75,
                'name' => 'Abductor Machine',
                'image' => 'abductor_machine.png',
                'description' => NULL,
                'muscle' => 'Abduttori',
            ],
            [
                'id' => 76,
                'name' => 'Abductor Machine Inversa',
                'image' => 'abductor_machine_inversa.png',
                'description' => NULL,
                'muscle' => 'Abduttori',
            ],
            [
                'id' => 77,
                'name' => 'Caperture Abductor Machine',
                'image' => 'caperture_abductor_machine.png',
                'description' => NULL,
                'muscle' => 'Abduttori',
            ],
            [
                'id' => 78,
                'name' => 'Slanci Esterni Al Cavo Basso',
                'image' => 'slanci_esterni_cavo_basso.png',
                'description' => NULL,
                'muscle' => 'Abduttori',
            ],
            [
                'id' => 79,
                'name' => 'Concentrato Manubrio Seduto',
                'image' => 'concentrato_manubrio_seduto.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 80,
                'name' => 'Curl Con Bilanciere',
                'image' => 'curl_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 81,
                'name' => 'Curl Ai Cavi Alti',
                'image' => 'curl_cavi_alti.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 82,
                'name' => 'Curl Al Cavo Basso',
                'image' => 'curl_cavo_basso.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 83,
                'name' => 'Curl Con Manubri Alternato',
                'image' => 'curl_manubri_alternato.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 84,
                'name' => 'Curl A Martello Alternato',
                'image' => 'curl_manubri_martello_alternato.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 85,
                'name' => 'Curl Con Manubri',
                'image' => 'curl_manubri.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 86,
                'name' => 'Curl Con Manubri Alternato Seduto',
                'image' => 'curl_manubri_alternato_seduto.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 87,
                'name' => 'Panca Scott Con Manubrio',
                'image' => 'panca_scott_con_manubrio.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 88,
                'name' => 'Panca Scott Con Bilanciere',
                'image' => 'panca_scott_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 89,
                'name' => 'Curl Con Manubri Seduto',
                'image' => 'curl_manubri_seduto.png',
                'description' => NULL,
                'muscle' => 'Bicipiti',
            ],
            [
                'id' => 90,
                'name' => 'Rotazione Manubrio Su Panca',
                'image' => 'rotazione_manubrio_su_panca.png',
                'description' => NULL,
                'muscle' => 'Avambracci',
            ],
            [
                'id' => 91,
                'name' => 'Curl Con Bilanciere Su Panca',
                'image' => 'curl_bilanciere_su_panca.png',
                'description' => NULL,
                'muscle' => 'Avambracci',
            ],
            [
                'id' => 92,
                'name' => 'Curl Con Bilanciere Presa Inversa',
                'image' => 'curl_inverso_bilanciere.png',
                'description' => NULL,
                'muscle' => 'Avambracci',
            ],
            [
                'id' => 93,
                'name' => 'Curl Presa Inversa Manubrio Su Panca',
                'image' => 'curl_presa_inversa_manubrio_su_panca.png',
                'description' => NULL,
                'muscle' => 'Avambracci',
            ],
            [
                'id' => 94,
                'name' => 'Curl Con Manubrio Su Panca',
                'image' => 'curl_manubrio_su_panca.png',
                'description' => NULL,
                'muscle' => 'Avambracci',
            ],
            [
                'id' => 95,
                'name' => 'Adduttori Fianco Con Fitball',
                'image' => 'adduttori_fianco_con_fitball.png',
                'description' => NULL,
                'muscle' => 'Adduttori',
            ],
            [
                'id' => 96,
                'name' => 'Adduttori Sdraiato Con Fitball',
                'image' => 'adduttori_fianco_con_fitball.png',
                'description' => NULL,
                'muscle' => 'Adduttori',
            ],
            [
                'id' => 97,
                'name' => 'Adduttori Slanci Al Cavo Basso',
                'image' => 'adduttori_slanci_al_cavo_basso.png',
                'description' => NULL,
                'muscle' => 'Adduttori',
            ],
            [
                'id' => 98,
                'name' => 'Adductor Machine',
                'image' => 'adductor_machine.png',
                'description' => NULL,
                'muscle' => 'Adduttori',
            ],
            [
                'id' => 99,
                'name' => 'Pinnate Gambe Alternate',
                'image' => 'pinnate_gambe_alternate.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 100,
                'name' => 'Alzate Gambe Tese Con Fitball',
                'image' => 'alzate_gambe_tese_con_fitball.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 101,
                'name' => 'Addominal Machine',
                'image' => 'addominal_machine.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 102,
                'name' => 'Crunch Gambe 90°',
                'image' => 'crunch_gambe_90.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 103,
                'name' => 'Crunch Gambe Su Fitball',
                'image' => 'crunch_gambe_su_fitball.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 104,
                'name' => 'Plank',
                'image' => 'plank.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 105,
                'name' => 'Sollevamento Gambe A 90° Con Sbarra',
                'image' => 'sollevamento_gambe_90_sbarra.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 106,
                'name' => 'Crunch Hyperxtension',
                'image' => 'crunch_hyperxtension.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
            [
                'id' => 107,
                'name' => 'Side Plank Su Gomito',
                'image' => 'side_plank_su_gomito.png',
                'description' => NULL,
                'muscle' => 'Addominali',
            ],
        ]);
    }
}